//
// GSFontLists.h
//
// Copyright (c) 2013 Gil Shapira
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

static NSDictionary *GSFontLists(void) {
    return @{

        @4.3f : @[
            @"AmericanTypewriter",
            @"AmericanTypewriter-Bold",
            @"AppleColorEmoji",
            @"AppleSDGothicNeo-Medium",
            @"Arial-BoldItalicMT",
            @"Arial-BoldMT",
            @"Arial-ItalicMT",
            @"ArialMT",
            @"ArialHebrew",
            @"ArialHebrew-Bold",
            @"ArialRoundedMTBold",
            @"BanglaSangamMN",
            @"BanglaSangamMN-Bold",
            @"Baskerville",
            @"Baskerville-Bold",
            @"Baskerville-BoldItalic",
            @"Baskerville-Italic",
            @"ChalkboardSE-Bold",
            @"ChalkboardSE-Regular",
            @"Cochin",
            @"Cochin-Bold",
            @"Cochin-BoldItalic",
            @"Cochin-Italic",
            @"Courier",
            @"Courier-Bold",
            @"Courier-BoldOblique",
            @"Courier-Oblique",
            @"CourierNewPS-BoldItalicMT",
            @"CourierNewPS-BoldMT",
            @"CourierNewPS-ItalicMT",
            @"CourierNewPSMT",
            @"DevanagariSangamMN",
            @"DevanagariSangamMN-Bold",
            @"Futura-CondensedExtraBold",
            @"Futura-Medium",
            @"Futura-MediumItalic",
            @"GeezaPro",
            @"GeezaPro-Bold",
            @"Georgia",
            @"Georgia-Bold",
            @"Georgia-BoldItalic",
            @"Georgia-Italic",
            @"GujaratiSangamMN",
            @"GujaratiSangamMN-Bold",
            @"GurmukhiMN",
            @"GurmukhiMN-Bold",
            @"STHeitiSC-Light",
            @"STHeitiSC-Medium",
            @"STHeitiTC-Light",
            @"STHeitiTC-Medium",
            @"Helvetica",
            @"Helvetica-Bold",
            @"Helvetica-BoldOblique",
            @"Helvetica-Oblique",
            @"HelveticaNeue",
            @"HelveticaNeue-Bold",
            @"HelveticaNeue-BoldItalic",
            @"HelveticaNeue-Italic",
            @"HiraKakuProN-W3",
            @"HiraMinProN-W3",
            @"HiraMinProN-W6",
            @"Kailasa",
            @"Kailasa-Bold",
            @"KannadaSangamMN",
            @"KannadaSangamMN-Bold",
            @"MalayalamSangamMN",
            @"MalayalamSangamMN-Bold",
            @"MarkerFelt-Thin",
            @"MarkerFelt-Wide",
            @"OriyaSangamMN",
            @"OriyaSangamMN-Bold",
            @"Palatino-Bold",
            @"Palatino-BoldItalic",
            @"Palatino-Italic",
            @"Palatino-Roman",
            @"SinhalaSangamMN",
            @"SinhalaSangamMN-Bold",
            @"SnellRoundhand",
            @"SnellRoundhand-Bold",
            @"TamilSangamMN",
            @"TamilSangamMN-Bold",
            @"TeluguSangamMN",
            @"TeluguSangamMN-Bold",
            @"Thonburi",
            @"Thonburi-Bold",
            @"TimesNewRomanPS-BoldItalicMT",
            @"TimesNewRomanPS-BoldMT",
            @"TimesNewRomanPS-ItalicMT",
            @"TimesNewRomanPSMT",
            @"Trebuchet-BoldItalic",
            @"TrebuchetMS",
            @"TrebuchetMS-Bold",
            @"TrebuchetMS-Italic",
            @"Verdana",
            @"Verdana-Bold",
            @"Verdana-BoldItalic",
            @"Verdana-Italic",
            @"Zapfino",
        ],

        @5.0f : @[
            @"AcademyEngravedLetPlain",
            @"AmericanTypewriter-Condensed",
            @"AmericanTypewriter-CondensedBold",
            @"AmericanTypewriter-CondensedLight",
            @"AmericanTypewriter-Light",
            @"AppleSDGothicNeo-Bold",
            @"Baskerville-SemiBold",
            @"Baskerville-SemiBoldItalic",
            @"BodoniSvtyTwoITCTT-Bold",
            @"BodoniSvtyTwoITCTT-Book",
            @"BodoniSvtyTwoITCTT-BookIta",
            @"BodoniSvtyTwoOSITCTT-Bold",
            @"BodoniSvtyTwoOSITCTT-Book",
            @"BodoniSvtyTwoOSITCTT-BookIt",
            @"BodoniSvtyTwoSCITCTT-Book",
            @"BodoniOrnamentsITCTT",
            @"ChalkboardSE-Light",
            @"Chalkduster",
            @"Copperplate",
            @"Copperplate-Bold",
            @"Copperplate-Light",
            @"Didot",
            @"Didot-Bold",
            @"Didot-Italic",
            @"EuphemiaUCAS",
            @"EuphemiaUCAS-Bold",
            @"EuphemiaUCAS-Italic",
            @"Futura-CondensedMedium",
            @"GillSans",
            @"GillSans-Bold",
            @"GillSans-BoldItalic",
            @"GillSans-Italic",
            @"GillSans-Light",
            @"GillSans-LightItalic",
            @"Helvetica-Light",
            @"Helvetica-LightOblique",
            @"HelveticaNeue-CondensedBlack",
            @"HelveticaNeue-CondensedBold",
            @"HelveticaNeue-Light",
            @"HelveticaNeue-LightItalic",
            @"HelveticaNeue-Medium",
            @"HelveticaNeue-UltraLight",
            @"HelveticaNeue-UltraLightItalic",
            @"HiraKakuProN-W6",
            @"HoeflerText-Black",
            @"HoeflerText-BlackItalic",
            @"HoeflerText-Italic",
            @"HoeflerText-Regular",
            @"Marion-Bold",
            @"Marion-Italic",
            @"Marion-Regular",
            @"Noteworthy-Bold",
            @"Noteworthy-Light",
            @"Optima-Bold",
            @"Optima-BoldItalic",
            @"Optima-ExtraBlack",
            @"Optima-Italic",
            @"Optima-Regular",
            @"Papyrus",
            @"Papyrus-Condensed",
            @"PartyLetPlain",
            @"SnellRoundhand-Black",
            @"ZapfDingbatsITC",
        ],

        @6.0f : @[
            @"Avenir-Black",
            @"Avenir-BlackOblique",
            @"Avenir-Book",
            @"Avenir-BookOblique",
            @"Avenir-Heavy",
            @"Avenir-HeavyOblique",
            @"Avenir-Light",
            @"Avenir-LightOblique",
            @"Avenir-Medium",
            @"Avenir-MediumOblique",
            @"Avenir-Oblique",
            @"Avenir-Roman",
            @"AvenirNext-Bold",
            @"AvenirNext-BoldItalic",
            @"AvenirNext-DemiBold",
            @"AvenirNext-DemiBoldItalic",
            @"AvenirNext-Heavy",
            @"AvenirNext-HeavyItalic",
            @"AvenirNext-Italic",
            @"AvenirNext-Medium",
            @"AvenirNext-MediumItalic",
            @"AvenirNext-Regular",
            @"AvenirNext-UltraLight",
            @"AvenirNext-UltraLightItalic",
            @"AvenirNextCondensed-Bold",
            @"AvenirNextCondensed-BoldItalic",
            @"AvenirNextCondensed-DemiBold",
            @"AvenirNextCondensed-DemiBoldItalic",
            @"AvenirNextCondensed-Heavy",
            @"AvenirNextCondensed-HeavyItalic",
            @"AvenirNextCondensed-Italic",
            @"AvenirNextCondensed-Medium",
            @"AvenirNextCondensed-MediumItalic",
            @"AvenirNextCondensed-Regular",
            @"AvenirNextCondensed-UltraLight",
            @"AvenirNextCondensed-UltraLightItalic",
            @"BradleyHandITCTT-Bold",
            @"Symbol",
        ],
        
        @7.0f : @[
            @"AlNile",
            @"AlNile-Bold",
            @"AppleSDGothicNeo-Light",
            @"AppleSDGothicNeo-Regular",
            @"AppleSDGothicNeo-SemiBold",
            @"AppleSDGothicNeo-Thin",
            @"ArialHebrew-Light",
            @"DINAlternate-Bold",
            @"DINCondensed-Bold",
            @"Damascus",
            @"DamascusBold",
            @"DamascusMedium",
            @"DamascusSemiBold",
            @"DiwanMishafi",
            @"Farah",
            @"GeezaPro-Light",
            @"HelveticaNeue-MediumItalic",
            @"HelveticaNeue-Thin",
            @"HelveticaNeue-ThinItalic",
            @"IowanOldStyle-Bold",
            @"IowanOldStyle-BoldItalic",
            @"IowanOldStyle-Italic",
            @"IowanOldStyle-Roman",
            @"Menlo-Bold",
            @"Menlo-BoldItalic",
            @"Menlo-Italic",
            @"Menlo-Regular",
            @"SavoyeLetPlain",
            @"Superclarendon-Black",
            @"Superclarendon-BlackItalic",
            @"Superclarendon-Bold",
            @"Superclarendon-BoldItalic",
            @"Superclarendon-Italic",
            @"Superclarendon-Light",
            @"Superclarendon-LightItalic",
            @"Superclarendon-Regular",
            @"Thonburi-Light",
        ]

    };
}
